#markdown: GFM
theme: jekyll-theme-modernist
#remote_theme: pages-themes/modernist@v0.2.0  # https://github.com/pages-themes/modernist?tab=readme-ov-file#usage
#plugins:
#  - jekyll-relative-links
#  #- jekyll-remote-theme
#relative_links:
#  - enabled: true
#  - collections: true
